<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>KOF98.CsSim</RootNamespace>
    <AssemblyName>KOF98.CsSim</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.cs" Exclude="obj/**;bin/**" />
    <ProjectReference Include="../KOF98.Game/KOF98.Game.csproj" />
  </ItemGroup>
</Project>
