namespace FFVM
{
    /// <summary>
    /// Lang-7: Auto-degradation type for exported functions.
    /// Compiler detects pure getter/setter patterns and marks them for
    /// automatic optimization: XCALL → XLOAD_MVAR or XSTORE_MVAR.
    /// </summary>
    public enum DegradationType : byte
    {
        /// <summary>No degradation — must use XCALL.</summary>
        None = 0,
        /// <summary>Pure getter — can be replaced with XLOAD_MVAR (read target module var directly).</summary>
        Getter = 1,
        /// <summary>Pure setter — can be replaced with XSTORE_MVAR (write target module var directly).</summary>
        Setter = 2,
    }

    /// <summary>
    /// Lang-6: Export table for cross-instance member access (XIMA).
    /// Generated by compiler for modules containing @export declarations.
    /// Stored in VMProgram (ROM, shared across instances of same module).
    /// </summary>
    public class ExportTable
    {
        /// <summary>Exported variable entries, indexed by export var index (0-based).</summary>
        public readonly ExportVarEntry[] Variables;

        /// <summary>Exported function entries, indexed by export func index (0-based).</summary>
        public readonly ExportFuncEntry[] Functions;

        public ExportTable(ExportVarEntry[] variables, ExportFuncEntry[] functions)
        {
            Variables = variables ?? System.Array.Empty<ExportVarEntry>();
            Functions = functions ?? System.Array.Empty<ExportFuncEntry>();
        }

        /// <summary>
        /// Lang-10: Resolve variable names to export indices (0-based).
        /// One-time name→index mapping; result can be cached and reused across instances.
        /// Returns -1 for names not found in the export table.
        /// </summary>
        public int[] ResolveVarIndices(string[] names)
        {
            if (names == null) return System.Array.Empty<int>();
            var indices = new int[names.Length];
            for (int i = 0; i < names.Length; i++)
            {
                indices[i] = -1; // not found sentinel
                for (int j = 0; j < Variables.Length; j++)
                {
                    if (Variables[j].Name == names[i])
                    {
                        indices[i] = j;
                        break;
                    }
                }
            }
            return indices;
        }

        /// <summary>
        /// Lang-10: Batch read default values by pre-resolved indices.
        /// O(1) per index (direct array access). Invalid indices (negative) yield Number.Zero.
        /// </summary>
        public Number[] ReadVarDefaults(int[] indices)
        {
            if (indices == null) return System.Array.Empty<Number>();
            var values = new Number[indices.Length];
            for (int i = 0; i < indices.Length; i++)
            {
                int idx = indices[i];
                values[i] = (idx >= 0 && idx < Variables.Length) ? Variables[idx].DefaultValue : Number.Zero;
            }
            return values;
        }

        /// <summary>
        /// Lang-10: Convenience single-variable default value lookup.
        /// Linear search by name; returns fallback if not found.
        /// For batch / high-frequency use, prefer ResolveVarIndices + ReadVarDefaults.
        /// </summary>
        public Number GetVarDefault(string name, Number fallback)
        {
            for (int i = 0; i < Variables.Length; i++)
            {
                if (Variables[i].Name == name)
                    return Variables[i].DefaultValue;
            }
            return fallback;
        }
    }

    /// <summary>Exported variable: maps export index → module variable slot + metadata.</summary>
    public struct ExportVarEntry
    {
        /// <summary>Variable name (for debugging / LSP / cross-module resolution).</summary>
        public readonly string Name;

        /// <summary>
        /// Module variable slot (0-based offset from ModuleVarRegBase).
        /// For fixed module vars: physical register = ModuleVarRegBase + MvarSlot.
        /// For extended module vars (MvarSlot >= ModuleVarSlots): extended register index = MvarSlot - ModuleVarSlots.
        /// </summary>
        public readonly int MvarSlot;

        /// <summary>True if declared as @export var (read-write). False if @export const (read-only).</summary>
        public readonly bool Writable;

        /// <summary>
        /// Lang-10: Compile-time default value of the exported variable.
        /// Stores the constant-folded initializer value (e.g. @export var hp: int = 100 → DefaultValue = 100).
        /// Variables without an initializer default to Number.Zero.
        /// </summary>
        public readonly Number DefaultValue;

        public ExportVarEntry(string name, int mvarSlot, bool writable)
        {
            Name = name;
            MvarSlot = mvarSlot;
            Writable = writable;
            DefaultValue = Number.Zero;
        }

        /// <summary>Lang-10: Constructor with compile-time default value.</summary>
        public ExportVarEntry(string name, int mvarSlot, bool writable, Number defaultValue)
        {
            Name = name;
            MvarSlot = mvarSlot;
            Writable = writable;
            DefaultValue = defaultValue;
        }
    }

    /// <summary>Exported function: maps export index → function table entry + metadata.</summary>
    public struct ExportFuncEntry
    {
        /// <summary>Function name (for debugging / LSP / cross-module resolution).</summary>
        public readonly string Name;

        /// <summary>Index into VMProgram.Functions array.</summary>
        public readonly int FuncTableIndex;

        /// <summary>Parameter count (for argument validation).</summary>
        public readonly int ParamCount;

        /// <summary>
        /// Lang-7: Auto-degradation type. Getter → XLOAD_MVAR, Setter → XSTORE_MVAR.
        /// None = must use XCALL (default, backward-compatible).
        /// </summary>
        public readonly DegradationType Degradation;

        /// <summary>
        /// Lang-7: Target module variable slot for degraded access.
        /// Only valid when Degradation != None.
        /// For Getter: the mvar slot to XLOAD_MVAR from.
        /// For Setter: the mvar slot to XSTORE_MVAR to.
        /// </summary>
        public readonly int DegradeMvarSlot;

        /// <summary>
        /// Lang-8: @inline hint flag. True if the function was declared with @inline.
        /// Currently informational only (used by LSP diagnostics).
        /// </summary>
        public readonly bool IsInlineHint;

        public ExportFuncEntry(string name, int funcTableIndex, int paramCount)
        {
            Name = name;
            FuncTableIndex = funcTableIndex;
            ParamCount = paramCount;
            Degradation = DegradationType.None;
            DegradeMvarSlot = -1;
            IsInlineHint = false;
        }

        public ExportFuncEntry(string name, int funcTableIndex, int paramCount,
            DegradationType degradation, int degradeMvarSlot)
        {
            Name = name;
            FuncTableIndex = funcTableIndex;
            ParamCount = paramCount;
            Degradation = degradation;
            DegradeMvarSlot = degradeMvarSlot;
            IsInlineHint = false;
        }

        public ExportFuncEntry(string name, int funcTableIndex, int paramCount,
            DegradationType degradation, int degradeMvarSlot, bool isInlineHint)
        {
            Name = name;
            FuncTableIndex = funcTableIndex;
            ParamCount = paramCount;
            Degradation = degradation;
            DegradeMvarSlot = degradeMvarSlot;
            IsInlineHint = isInlineHint;
        }
    }

    /// <summary>
    /// Lang-9 P3: Compilation artifacts needed for cross-module inline.
    /// Stored in CompileResult and optionally passed through ServiceBinding.
    /// Contains function ASTs, module variable export indices, and const values
    /// so the caller compiler can inline the callee's function bodies.
    /// </summary>
    public class ModuleInlineInfo
    {
        /// <summary>
        /// Function ASTs of exported functions (name → FuncDecl).
        /// Only exported functions are included (caller can only call exported functions).
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<string, FFVM.AST.FuncDecl> FuncDecls;

        /// <summary>
        /// Exported module variable names → export var index (0-based into ExportTable.Variables).
        /// Only exported variables are included (XLOAD_MVAR/XSTORE_MVAR requires export var index).
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<string, int> VarExportIndices;

        /// <summary>
        /// Module const name → folded compile-time value.
        /// Used for cross-module const propagation during inline.
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<string, Number> ConstValues;

        /// <summary>
        /// All function names in the callee module (exported and non-exported).
        /// Used to distinguish callee user function calls from syscalls during inline safety checks.
        /// </summary>
        public readonly System.Collections.Generic.HashSet<string> AllFuncNames;

        public ModuleInlineInfo(
            System.Collections.Generic.Dictionary<string, FFVM.AST.FuncDecl> funcDecls,
            System.Collections.Generic.Dictionary<string, int> varExportIndices,
            System.Collections.Generic.Dictionary<string, Number> constValues,
            System.Collections.Generic.HashSet<string> allFuncNames)
        {
            FuncDecls = funcDecls;
            VarExportIndices = varExportIndices;
            ConstValues = constValues;
            AllFuncNames = allFuncNames;
        }
    }

    /// <summary>
    /// Lang-8: Service binding — maps a local variable name to a target module's ExportTable.
    /// Passed to the compiler so it can resolve svc.member unified syntax.
    /// </summary>
    public class ServiceBinding
    {
        /// <summary>Local variable name in the caller script (e.g. "svc").</summary>
        public readonly string VarName;

        /// <summary>Target module's export table (pre-compiled).</summary>
        public readonly ExportTable Exports;

        /// <summary>
        /// Lang-9 P3: Optional inline info for cross-module inline.
        /// When present, enables inlining of the callee's exported functions.
        /// </summary>
        public readonly ModuleInlineInfo InlineInfo;

        public ServiceBinding(string varName, ExportTable exports)
        {
            VarName = varName;
            Exports = exports;
            InlineInfo = null;
        }

        /// <summary>Lang-9 P3: Constructor with inline info for cross-module inline support.</summary>
        public ServiceBinding(string varName, ExportTable exports, ModuleInlineInfo inlineInfo)
        {
            VarName = varName;
            Exports = exports;
            InlineInfo = inlineInfo;
        }
    }

    /// <summary>
    /// Lang-6: Cross-instance call frame. Saved/restored on XCALL entry/exit.
    /// Stored in VMWorld (not in VMInstanceState) since it spans instances.
    /// </summary>
    public struct XCallFrame
    {
        public int CallerInstanceId;
        public int CallerIP;
        public int CallerModuleSlot;
        public int CallerRegisterBase;
        public int CallerCallStackDepth;
        public int CallerCleanupDepth;
        public int DestReg;             // caller's return-value destination register (already Reg()-mapped)
    }
}
