namespace FFVM
{
    /// <summary>
    /// Lang-7: Auto-degradation type for exported functions.
    /// Compiler detects pure getter/setter patterns and marks them for
    /// automatic optimization: XCALL → XLOAD_MVAR or XSTORE_MVAR.
    /// </summary>
    public enum DegradationType : byte
    {
        /// <summary>No degradation — must use XCALL.</summary>
        None = 0,
        /// <summary>Pure getter — can be replaced with XLOAD_MVAR (read target module var directly).</summary>
        Getter = 1,
        /// <summary>Pure setter — can be replaced with XSTORE_MVAR (write target module var directly).</summary>
        Setter = 2,
    }

    /// <summary>
    /// Lang-6: Export table for cross-instance member access (XIMA).
    /// Generated by compiler for modules containing @export declarations.
    /// Stored in VMProgram (ROM, shared across instances of same module).
    /// </summary>
    public class ExportTable
    {
        /// <summary>Exported variable entries, indexed by export var index (0-based).</summary>
        public readonly ExportVarEntry[] Variables;

        /// <summary>Exported function entries, indexed by export func index (0-based).</summary>
        public readonly ExportFuncEntry[] Functions;

        public ExportTable(ExportVarEntry[] variables, ExportFuncEntry[] functions)
        {
            Variables = variables ?? System.Array.Empty<ExportVarEntry>();
            Functions = functions ?? System.Array.Empty<ExportFuncEntry>();
        }
    }

    /// <summary>Exported variable: maps export index → module variable slot + metadata.</summary>
    public struct ExportVarEntry
    {
        /// <summary>Variable name (for debugging / LSP / cross-module resolution).</summary>
        public readonly string Name;

        /// <summary>
        /// Module variable slot (0-based offset from ModuleVarRegBase).
        /// For fixed module vars: physical register = ModuleVarRegBase + MvarSlot.
        /// For extended module vars (MvarSlot >= ModuleVarSlots): extended register index = MvarSlot - ModuleVarSlots.
        /// </summary>
        public readonly int MvarSlot;

        /// <summary>True if declared as @export var (read-write). False if @export const (read-only).</summary>
        public readonly bool Writable;

        public ExportVarEntry(string name, int mvarSlot, bool writable)
        {
            Name = name;
            MvarSlot = mvarSlot;
            Writable = writable;
        }
    }

    /// <summary>Exported function: maps export index → function table entry + metadata.</summary>
    public struct ExportFuncEntry
    {
        /// <summary>Function name (for debugging / LSP / cross-module resolution).</summary>
        public readonly string Name;

        /// <summary>Index into VMProgram.Functions array.</summary>
        public readonly int FuncTableIndex;

        /// <summary>Parameter count (for argument validation).</summary>
        public readonly int ParamCount;

        /// <summary>
        /// Lang-7: Auto-degradation type. Getter → XLOAD_MVAR, Setter → XSTORE_MVAR.
        /// None = must use XCALL (default, backward-compatible).
        /// </summary>
        public readonly DegradationType Degradation;

        /// <summary>
        /// Lang-7: Target module variable slot for degraded access.
        /// Only valid when Degradation != None.
        /// For Getter: the mvar slot to XLOAD_MVAR from.
        /// For Setter: the mvar slot to XSTORE_MVAR to.
        /// </summary>
        public readonly int DegradeMvarSlot;

        public ExportFuncEntry(string name, int funcTableIndex, int paramCount)
        {
            Name = name;
            FuncTableIndex = funcTableIndex;
            ParamCount = paramCount;
            Degradation = DegradationType.None;
            DegradeMvarSlot = -1;
        }

        public ExportFuncEntry(string name, int funcTableIndex, int paramCount,
            DegradationType degradation, int degradeMvarSlot)
        {
            Name = name;
            FuncTableIndex = funcTableIndex;
            ParamCount = paramCount;
            Degradation = degradation;
            DegradeMvarSlot = degradeMvarSlot;
        }
    }

    /// <summary>
    /// Lang-6: Cross-instance call frame. Saved/restored on XCALL entry/exit.
    /// Stored in VMWorld (not in VMInstanceState) since it spans instances.
    /// </summary>
    public struct XCallFrame
    {
        public int CallerInstanceId;
        public int CallerIP;
        public int CallerModuleSlot;
        public int CallerRegisterBase;
        public int CallerCallStackDepth;
        public int CallerCleanupDepth;
        public int DestReg;             // caller's return-value destination register (already Reg()-mapped)
    }
}
