namespace FFVM.Compiler
{
    /// <summary>
    /// CFG1: Configurable compiler options.
    /// All values have sensible defaults matching the original hardcoded constants.
    /// Pass to BytecodeCompiler.Compile() to override; null = use defaults.
    ///
    /// <para><b>Design principle</b>: these options are "knobs" that trade off between
    /// compilation aggressiveness and safety margins. Changing a value never breaks
    /// correctness — it only affects code-generation strategy and resource usage.</para>
    ///
    /// <para><b>Performance note</b>: options are read once at compile-time and cached.
    /// They impose zero runtime overhead on the generated bytecode execution.</para>
    /// </summary>
    public class CompileOptions
    {
        // ===== Inlining =====

        /// <summary>
        /// Maximum estimated instruction count for a function to be eligible for inlining.
        /// Functions with EstimateBodySize &gt; this value are compiled as regular CALL instructions.
        ///
        /// <para><b>↑ Increase</b>: more functions inlined → fewer CALL/RET pairs → less call overhead,
        /// but larger bytecode per call site, higher register pressure, longer compile time.
        /// May trigger "Expression too complex" if combined with deep nesting.</para>
        ///
        /// <para><b>↓ Decrease</b>: fewer inlines → smaller bytecode → lower register pressure,
        /// but more CALL/RET overhead per invocation. Setting to 0 disables inlining entirely.</para>
        ///
        /// <para><b>Default: 16</b>. Reasonable for most workloads. KOF-style skill scripts
        /// rarely exceed this; complex utility functions benefit from being kept as CALLs.</para>
        /// </summary>
        public int InlineThreshold { get; set; } = 16;

        /// <summary>
        /// Maximum nested inline depth. When the current inline nesting reaches this limit,
        /// further inline candidates are compiled as regular CALL/XCALL.
        ///
        /// <para><b>↑ Increase</b>: deeper inline chains → more aggressive optimization,
        /// but exponential growth in bytecode size and register usage.
        /// Risk: "Static register window depth exceeding available slots" error.</para>
        ///
        /// <para><b>↓ Decrease</b>: shallower inlining → more predictable resource usage.
        /// Setting to 0 disables inlining entirely (same as InlineThreshold=0).</para>
        ///
        /// <para><b>Default: 3</b>. Balances optimization depth vs. code explosion.
        /// Most real-world call chains are ≤3 deep in game scripting.</para>
        /// </summary>
        public int InlineDepthMax { get; set; } = 3;

        /// <summary>
        /// Maximum number of loop-invariant constants hoisted per loop (LICM optimization).
        /// Each hoisted constant occupies one local variable register for the loop's duration.
        ///
        /// <para><b>↑ Increase</b>: more constants hoisted → fewer redundant LOAD_CONST
        /// inside hot loops, but more registers consumed during the loop body.
        /// Risk: "Too many local variables" if loop body is already register-heavy.</para>
        ///
        /// <para><b>↓ Decrease</b>: fewer hoisted constants → more LOAD_CONST inside loops
        /// (each takes 1 cycle), but lower register pressure.
        /// Setting to 0 disables LICM entirely.</para>
        ///
        /// <para><b>Default: 8</b>. Covers typical loop patterns (counter, limit, step, accumulators).</para>
        /// </summary>
        public int MaxHoistedPerLoop { get; set; } = 8;

        // ===== Diagnostics =====

        /// <summary>
        /// When true, the compiler emits resource usage warnings when approaching limits.
        /// Warnings are non-fatal and appear in CompileResult.Warnings.
        ///
        /// <para>Examples: "Module uses 7/8 module variable slots (87%)",
        /// "Function 'update' uses 28/32 local variable slots (87%)",
        /// "Constant pool uses 230/256 entries before wide fallback".</para>
        ///
        /// <para><b>↑ Enable (true)</b>: early visibility into resource pressure —
        /// catches approaching-limit issues before they cause failures.
        /// No runtime cost (diagnostics run at compile-time only).</para>
        ///
        /// <para><b>↓ Disable (false)</b>: suppresses all [CFG1] warnings.
        /// Use in production builds where warning noise is undesirable.</para>
        ///
        /// <para><b>Default: true</b>. Recommended for development builds.</para>
        /// </summary>
        public bool DiagnosticsEnabled { get; set; } = true;

        /// <summary>
        /// Threshold (0.0–1.0) for resource usage warnings.
        /// A warning is emitted when usage ≥ this fraction of the limit.
        ///
        /// <para><b>↑ Increase (→1.0)</b>: warnings fire later → less noise,
        /// but less lead time to act before hitting hard limits.</para>
        ///
        /// <para><b>↓ Decrease (→0.0)</b>: warnings fire earlier → more visibility,
        /// but higher noise for modules well within limits.</para>
        ///
        /// <para><b>Default: 0.75</b> (75%). Warning fires when 3/4 of a resource is consumed.</para>
        /// </summary>
        public float DiagnosticsThreshold { get; set; } = 0.75f;
    }
}
